// Command emoji writes internal/emoji/table.go from emoji.json, which is
// iamcal/emoji-data's emoji.json (MIT; the names Slack uses) cut down to
// what's needed, in its sort order:
//
//	jq -c '[.[] | {short_names, unified, sort_order, category, skin_variations: (.skin_variations // {} | with_entries(select(.key | test("^1F3F[B-F]$"))) | map_values({unified}))}]
//	  | sort_by(.sort_order) | map(del(.sort_order) | if .skin_variations == {} then del(.skin_variations) else . end)' emoji.json
//
// Run it with go generate in internal/emoji. Nothing is fetched at build
// or run time.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
)

type entry struct {
	Names    []string `json:"short_names"`
	Code     string   `json:"unified"`
	Category string   `json:"category"`
	Skins    map[string]struct {
		Code string `json:"unified"`
	} `json:"skin_variations"`
}

// glyph reads iamcal's "1F44D-1F3FB" as the characters.
func glyph(code string) string {
	var b strings.Builder
	for _, h := range strings.Split(code, "-") {
		n, err := strconv.ParseUint(h, 16, 32)
		if err != nil {
			log.Fatalf("bad code %q", code)
		}
		b.WriteRune(rune(n))
	}
	return b.String()
}

func main() {
	raw, err := os.ReadFile("../../tools/emoji/emoji.json")
	if err != nil {
		log.Fatal(err)
	}
	var es []entry
	if err := json.Unmarshal(raw, &es); err != nil {
		log.Fatal(err)
	}
	// A line a glyph: its names, the glyph, then its five skin tones
	// (Slack's skin-tone-2 to 6) where it has them. Two-tone variants of
	// couples and handshakes are left out. "#Category" starts each of
	// iamcal's categories, which come in order.
	var b strings.Builder
	b.WriteString("// Code generated by tools/emoji; DO NOT EDIT.\n\npackage emoji\n\nconst data = \"\" +\n")
	category := ""
	for _, e := range es {
		if e.Category != category {
			category = e.Category
			fmt.Fprintf(&b, "\t%s +\n", strconv.Quote("#"+category+"\n"))
		}
		line := strings.Join(e.Names, ",") + "\t" + glyph(e.Code)
		if len(e.Skins) > 0 {
			for _, k := range []string{"1F3FB", "1F3FC", "1F3FD", "1F3FE", "1F3FF"} {
				line += "\t" + glyph(e.Skins[k].Code)
			}
		}
		fmt.Fprintf(&b, "\t%s +\n", strconv.Quote(line+"\n"))
	}
	b.WriteString("\t\"\"\n")
	if err := os.WriteFile("table.go", []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
}
